apiVersion: v1
kind: Secret
metadata:
  name: tx01-db-credentials
  namespace: default
type: Opaque
stringData:
  host: ${DB_HOST}
  port: "${DB_PORT}"
  dbname: ${DB_NAME}
  username: ${DB_USER}
  password: ${DB_PASSWORD}
