apiVersion: v1
kind: Service
metadata:
  name: tx01-service
  namespace: default
  labels:
    app: tx01
spec:
  type: ClusterIP
  selector:
    app: tx01
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  sessionAffinity: None
