apiVersion: v1
kind: Service
metadata:
  name: tx01-service
  namespace: default
  labels:
    app: tx01
    environment: ${ENVIRONMENT}
spec:
  type: NodePort
  selector:
    app: tx01
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  sessionAffinity: None
